#pragma once;
class Object;
class Light;
class Component;
class Button;
class Camera;
class Collider;
class BoxCollider;
class MeshCollider;
class SphereCollider;
class Mesh;
class Text;
class UI;
class Scene;
class BV;
class Box3D;
class Box2D;

class Render;
class Window;
class Transform;
class SpatialHashing;
class RenderToTexture;

#include "../Engine/Commons/common.h"
#include "../Engine/Datatypes/Utils/utils.h"
#include "../Engine/Datatypes/Shader/shader.h"
#include "../Engine/Datatypes/Texture/texture.h"
#include "../Engine/Datatypes/vertex.h"
#include "../Engine/Input/input.h"
#include "../Engine/Render/render.h"
#include "../Engine/Window/window.h"
#include "../Object/object.h"
#include "../Object/component.h"
#include "../Object/Light/light.h"
#include "../Object/Light/orbitalLight.h"
#include "../Object/Components/Button/button.h"
#include "../Object/Components/Camera/camera.h"
#include "../Object/Components/Collider/collider.h"
#include "../Object/Components/Collider/boxCollider.h"
#include "../Object/Components/Collider/sphereCollider.h"
#include "../Object/Components/Collider/meshCollider.h"
#include "../Object/Components/Mesh/mesh.h"
#include "../Object/Components/Text/text.h"
#include "../Object/Components/Transform/transform.h"
#include "../Object/Components/UI/ui.h"
#include "../Object/Components/RenderToTexture/render_to_texture.h"
#include "../Scene/scene.h"
#include "../Scene/spatialHashing.h"